"""empty message

Revision ID: 9deae7814532
Revises: 517e1cc645ee
Create Date: 2026-01-07 21:21:07.816567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9deae7814532'
down_revision: Union[str, Sequence[str], None] = '517e1cc645ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('state', sa.Enum('PENDING', 'DRAFT', 'DOINHG', 'DONE', 'TRASH', name='todostatus'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, foreign_key='users.id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todos')
    # ### end Alembic commands ###
